version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://100.72.182.23:27017/mydatabase
    depends_on:
      - mongo
    command: ["gunicorn", "-w", "4", "--timeout", "120", "-b", "0.0.0.0:5001", "app:app"]  

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./Desktop/raspberry/project_me/mongod.conf:/etc/mongod.conf

volumes:
  mongo_data:
